version: '3.1'

services:
  app:
    build: .
    ports:
      - 3030:3030
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "application"
      POSTGRES_USER: "application"
      POSTGRES_DB: "pybotlog"
    ports:
    - 5432:5432